version: '3.4'

networks:
  notifications.api:

services:
  notifications.api:
    container_name: notifications.api
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: src/API/Notifications.API/Dockerfile
    ports:
      - 5010:5010
      - 9010:9010
      - 5011:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:5010;http://+:9010;
      - GRPCCLIENT_NOTIFICATIONS_URL=http://host.docker.internal:9010
      - GITHUB_PASSWORD=password
    restart: always
    networks:
      - notifications.api
